feat: automatically trim leading relative path qualifier
trim off the leading relative path qualifier if present

diff --git a/.github/workflows/matrix-config.yml b/.github/workflows/matrix-config.yml
--- a/.github/workflows/matrix-config.yml
+++ b/.github/workflows/matrix-config.yml
@@ -4,27 +4,23 @@ on:
   workflow_call:
     inputs:
       config:
-        description: |
-          Path to your JSON config file. Example: `.github/deploy/dev.json`
-
-          NOTE: Do not include the leading relative path qualifier `./` in your
-          path unless setting `no-sparse-checkout` to `true`. Otherwise,
-          sparse checkout will not work.
+        description: >-
+          Path to your JSON config file.
+          Windows directory seperators (`\`) are not supported, be sure to use POSIX directory seperators (`/`).
+          Example: `.github/deploy/dev.json`
         type: string
         required: true
-
       no-sparse-checkout:
-        description: |
+        description: >-
           Do not use sparse checkout to fetch the config file from the repository.
           The default behavior is to only checkout the config file specified in the `config` input,
           and not the entire repository.
         type: boolean
         required: false
         default: false
-
     outputs:
       matrix:
-        description: |
+        description: >-
           A JSON escaped string that can be used as a job's [matrix strategy](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) configuration.
           Be sure to convert this stringified JSON to a JSON object (using `fromJson()` expression) when injecting into your job's stategy matrix.
         value: ${{ jobs.matrix-config.outputs.matrix }}
@@ -36,12 +32,27 @@ jobs:
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
     steps:
+      - name: Ensure only POSIX directory seperators
+        if: ${{ !fromJson(inputs.no-sparse-checkout) && contains(inputs.config, '\') }}
+        shell: pwsh
+        run: |
+          echo "::error title=✘ Invalid directory seperators::Sparse checkout does not support Windows directory seperators (back slashes), use forward slashes instead."
+          exit 1
+
+      - name: Trim leading relative path qualifier
+        id: trim-path
+        if: ${{ !fromJson(inputs.no-sparse-checkout) && startsWith(inputs.config, './') }}
+        shell: pwsh
+        run: |
+          $path = [Regex]::Replace('${{ inputs.config }}', '^\.\/', '')
+          Write-Output "path=$($path)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8NoBOM -Append
+
       - name: Checkout config file
         uses: actions/checkout@main
         if: ${{ !fromJson(inputs.no-sparse-checkout) }}
         with:
           sparse-checkout: |
-            ${{ inputs.config }}
+            ${{ steps.trim-path.outputs.path }}
           sparse-checkout-cone-mode: false
 
       - name: Checkout repository
